### ISSUE TITLE
Support terminal sequence colouring

### ISSUE THREAD

**Issue by pnutmath** [sumy7/monaco-language-log#1]
## Logs should be coloured according to Terminal Sequence colouring

**Here is a doc**
https://www.lihaoyi.com/post/BuildyourownCommandLinewithANSIescapecodes.html

**Comment by sumy7** [comment]
Thanks for your advice. This repo just highlight some key words in log.
You could copy and paste [language-log.js](https://github.com/sumy7/monaco-language-log/blob/main/language-log.js) code to you project and change the color.
